import pandas as pd
import pymysql as ps
def get_connection():
    conn = ps.connect(
        host = "localhost",
        user = "root",
        password= "Mano_rootsql0481",
        database= "cross_market_analysis",
    )
    return conn
querries = {"TOP 3 CRYPTOCURRENCIES": "SELECT * FROM CRYPTOCURRENCIES WHERE MARKET_CAP_RANK <= 3 ORDER BY MARKET_CAP_RANK",
            "HIGHLY CIRCULATING SUPPLY": "SELECT NAME FROM CRYPTOCURRENCIES WHERE CIRCULATING_SUPPLY > (0.9*TOTAL_SUPPLY) ORDER BY MARKET_CAP_RANK",
            "WITHIN 10% OF ATH": "SELECT NAME FROM CRYPTOCURRENCIES WHERE CURRENT_PRICE >= (0.9*ATH) AND CURRENT_PRICE <= ATH ORDER BY MARKET_CAP_RANK",
            "AVERAGE MARKET CAP RANK OF COINS WITH VOLUME BELOW ₹1BN": "SELECT AVG(MARKET_CAP_RANK) AS AVG_RANK FROM CRYPTOCURRENCIES WHERE TOTAL_VOLUME < 1000000000",
            "MOST RECENTLY UPDATED COIN": "SELECT NAME, LAST_UPDATED FROM CRYPTOCURRENCIES ORDER BY LAST_UPDATED DESC",
            "HIGHEST DAILY PRICE OF BITCOIN": "SELECT MAX(PRICE_INR) AS HIGHEST_PRICE FROM CRYPTO_PRICES WHERE COIN_ID = 'BITCOIN'",
            "AVERAGE DAILY PRICE OF ETHEREUM": "SELECT AVG(PRICE_INR) AS AVERAGE_PRICE FROM CRYPTO_PRICES WHERE COIN_ID = 'ETHEREUM'",
            "DAILY PRICE TREND OF BITCOIN IN DECEMBER 2025": "SELECT DATE, PRICE_INR FROM CRYPTO_PRICES WHERE COIN_ID = 'BITCOIN' AND DATE >= '2025-12-01' AND DATE <= '2025-12-31' ORDER BY DATE",
            "COIN WITH HIGHEST AVERAGE PRICE": "SELECT COIN_ID, AVG(PRICE_INR) AS AVERAGE_PRICE FROM CRYPTO_PRICES GROUP BY COIN_ID ORDER BY AVERAGE_PRICE DESC LIMIT 1",
            "% CHANGE IN BITCOIN PRICE BETWEEN APRIL 2025 AND JANUARY 2026": "SELECT((jan.PRICE_INR - apr.PRICE_INR) / apr.PRICE_INR) * 100 AS PERCENT_CHANGE FROM CRYPTO_PRICES jan JOIN CRYPTO_PRICES apr ON jan.COIN_ID = apr.COIN_ID AND jan.DATE = '2026-01-01' AND apr.DATE = '2025-04-01' WHERE jan.COIN_ID = 'BITCOIN'",
            "HIGHEST OIL PRICE IN LAST 5 YEARS": "SELECT MAX(PRICE_INR) AS HIGHEST_OIL_PRICE FROM OIL_PRICES WHERE DATE >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR)",
            "AVERAGE OF OIL PRICE PER YEAR": "SELECT YEAR(DATE) AS YEAR, AVG(PRICE_INR) AS AVERAGE_PRICE_INR FROM OIL_PRICES GROUP BY YEAR ORDER BY YEAR",
            "OIL PRICES DURING COVID CRASH": "SELECT DATE, PRICE_INR FROM OIL_PRICES WHERE DATE >= '2020-03-01' AND DATE <= '2020-04-30' ORDER BY DATE",
            "LOWEST OIL PRICE IN LAST 5 YEARS": "SELECT MIN(PRICE_INR) AS LOWEST_OIL_PRICE FROM OIL_PRICES WHERE DATE >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR)",
            "VOLATILITY OF OIL PRICES PER YEAR": "SELECT YEAR(DATE) AS YEAR, (MAX(PRICE_INR) - MIN(PRICE_INR)) AS VOLATILITY FROM OIL_PRICES GROUP BY YEAR ORDER BY YEAR",
            "ALL STOCK PRICE FOR A GIVEN TICKER": " SELECT * FROM STOCK_PRICES WHERE TICKER = 'GSPC' ORDER BY DATE",
            "HIGHEST CLOSING PRICE OF NASDAQ": "SELECT MAX(CLOSE) AS HIGHEST_CLOSING_PRICE FROM STOCK_PRICES WHERE TICKER = 'IXIC'",
            "TOP 5 HIGHEST PRICE DIFFERENCE FOR GSPC": "SELECT DATE, (HIGH - LOW) AS PRICE_DIFFERENCE FROM STOCK_PRICES WHERE TICKER = 'GSPC' ORDER BY PRICE_DIFFERENCE DESC LIMIT 5",
            "MONTHLY AVERAGE OF CLOSING PRICE FOR EACH TICKER": "SELECT TICKER, YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH, AVG(CLOSE) AS AVERAGE_CLOSING_PRICE FROM STOCK_PRICES GROUP BY TICKER, YEAR(DATE), MONTH(DATE) ORDER BY TICKER, YEAR, MONTH",
            "AVERAGE TRADING VOLUME OF NSEI IN 2024": "SELECT AVG(VOLUME) AS AVERAGE_TRADING_VOLUME FROM STOCK_PRICES WHERE TICKER = 'NSEI' AND YEAR(DATE) = 2024",
            "Compare Bitcoin vs Oil average price in 2025": "SELECT CRYPTO_PRICES.DATE, CRYPTO_PRICES.PRICE_INR AS BITCOIN_PRICE, OIL_PRICES.PRICE_INR AS OIL_PRICE FROM CRYPTO_PRICES LEFT JOIN OIL_PRICES ON CRYPTO_PRICES.DATE = OIL_PRICES.DATE WHERE CRYPTO_PRICES.COIN_ID = 'BITCOIN' AND YEAR(CRYPTO_PRICES.DATE) = 2025 ORDER BY CRYPTO_PRICES.DATE",
            "CHECK IF BITCOIN MOVES WITH S&P 500": "SELECT CRYPTO_PRICES.DATE, CRYPTO_PRICES.PRICE_INR AS BITCOIN_PRICE, STOCK_PRICES.CLOSE AS SP500_CLOSE FROM CRYPTO_PRICES JOIN STOCK_PRICES ON CRYPTO_PRICES.DATE = STOCK_PRICES.DATE WHERE CRYPTO_PRICES.COIN_ID = 'BITCOIN' AND STOCK_PRICES.TICKER = 'GSPC' ORDER BY CRYPTO_PRICES.DATE",
            "COMPARE ETHERIUM AND NASDAQ DAILY PRICES IN 2025": "SELECT CRYPTO_PRICES.DATE, CRYPTO_PRICES.PRICE_INR AS ETHEREUM_PRICE, STOCK_PRICES.CLOSE AS NASDAQ_CLOSE FROM CRYPTO_PRICES JOIN STOCK_PRICES ON CRYPTO_PRICES.DATE = STOCK_PRICES.DATE WHERE CRYPTO_PRICES.COIN_ID = 'ETHEREUM' AND YEAR(CRYPTO_PRICES.DATE) = 2025 AND STOCK_PRICES.TICKER = 'IXIC' ORDER BY CRYPTO_PRICES.DATE",
            "OIL SPIKED AND BITCOIN PRICE CAHNGED":"SELECT o1.DATE, o1.PRICE_INR AS OIL_PRICE, c.PRICE_INR AS BTC_PRICE FROM OIL_PRICES o1 JOIN OIL_PRICES o2 ON o1.DATE = DATE_ADD(o2.DATE, INTERVAL 1 DAY) JOIN CRYPTO_PRICES c ON o1.DATE = c.DATE WHERE c.COIN_ID = 'bitcoin' AND o1.PRICE_INR > o2.PRICE_INR ORDER BY o1.DATE;",
            "TOP 3 COINS VS NIFTY":"SELECT c.DATE, c.COIN_ID, c.PRICE_INR AS COIN_PRICE, s.CLOSE AS NIFTY_CLOSE FROM CRYPTO_PRICES c JOIN (SELECT ID FROM CRYPTOCURRENCIES ORDER BY MARKET_CAP DESC LIMIT 3) top3 ON c.COIN_ID=top3.ID JOIN STOCK_PRICES s ON c.DATE=s.DATE AND s.TICKER='NSEI' ORDER BY c.DATE, c.COIN_ID;",
            "COMPARE STOCK PRICE WITH OIL":"SELECT s.DATE, s.CLOSE AS STOCK_PRICE, o.PRICE_INR AS OIL_PRICE FROM STOCK_PRICES s JOIN OIL_PRICES o ON s.DATE=o.DATE WHERE s.TICKER='GSPC' ORDER BY s.DATE;",
            "CORELATE BITCOIN WITH OIL":"SELECT c.DATE, c.PRICE_INR AS BTC_PRICE, o.PRICE_INR AS OIL_PRICE FROM CRYPTO_PRICES c JOIN OIL_PRICES o ON c.DATE=o.DATE WHERE c.COIN_ID='bitcoin' ORDER BY c.DATE;",
            "NASDAQ VS ETHERUM DAILY PRICE":"SELECT c.DATE, c.PRICE_INR AS ETH_PRICE, s.CLOSE AS NASDAQ_CLOSE FROM CRYPTO_PRICES c JOIN STOCK_PRICES s ON c.DATE=s.DATE WHERE c.COIN_ID='ethereum' AND s.TICKER='IXIC' ORDER BY c.DATE;",
            "TOP 3 CRYPTO WITH STOCK INDECES 2025":"SELECT c.DATE, c.COIN_ID, c.PRICE_INR AS COIN_PRICE, s.CLOSE AS STOCK_CLOSE, s.TICKER FROM CRYPTO_PRICES c JOIN (SELECT ID FROM CRYPTOCURRENCIES ORDER BY MARKET_CAP DESC LIMIT 3) top3 ON c.COIN_ID=top3.ID JOIN STOCK_PRICES s ON c.DATE=s.DATE WHERE s.DATE BETWEEN '2025-01-01' AND '2025-12-31' ORDER BY c.DATE, c.COIN_ID;",
            "MULTI JOIN FOR DAILY COMAPRISON":"SELECT s.DATE, s.CLOSE AS STOCK_PRICE, o.PRICE_INR AS OIL_PRICE, c.PRICE_INR AS BTC_PRICE FROM STOCK_PRICES s JOIN OIL_PRICES o ON s.DATE=o.DATE JOIN CRYPTO_PRICES c ON s.DATE=c.DATE WHERE s.TICKER='GSPC' AND c.COIN_ID='bitcoin' ORDER BY s.DATE;"}
def run_query(sql):
    conn = get_connection()
    df = pd.read_sql(sql, conn)
    conn.close()
    return df